import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:image_picker/image_picker.dart';
import 'package:padi_learn/screens/components/primary_button.dart';
import 'package:padi_learn/screens/teacher/components/upload_progress_card.dart';
import 'package:padi_learn/services/supabase.dart';
import 'package:padi_learn/services/supabase_storage_service.dart';
import 'package:padi_learn/utils/colors.dart';

class CreateCourseScreen extends StatefulWidget {
  const CreateCourseScreen({super.key});

  @override
  _CreateCourseScreenState createState() => _CreateCourseScreenState();
}

class _CreateCourseScreenState extends State<CreateCourseScreen> {
  final _formKey = GlobalKey<FormState>();
  final TextEditingController _titleController = TextEditingController();
  final TextEditingController _priceController = TextEditingController();
  final TextEditingController _descriptionController = TextEditingController();
  final TextEditingController _authorController = TextEditingController();
  String? _selectedCategory;
  File? _videoFile;
  File? _thumbnailFile;
  int _videoBytes = 0;
  int _thumbnailBytes = 0;
  bool _isLoading = false;

  /// Live upload progress; null when no upload is running.
  UploadProgress? _progress;

  final List<String> _categories = [
    'Programming',
    'Design',
    'Marketing',
    'Business',
    'Data Science',
  ];

  void _showMessage(String message, {bool isError = false}) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: isError ? Colors.red : null,
        duration: Duration(seconds: isError ? 5 : 3),
      ),
    );
  }

  Future<void> _pickVideo() async {
    final pickedFile =
        await ImagePicker().pickVideo(source: ImageSource.gallery);
    if (pickedFile == null) return;

    // Check the size now rather than after a long upload the server would
    // refuse anyway.
    final file = File(pickedFile.path);
    final bytes = await file.length();
    if (bytes > kMaxVideoBytes) {
      _showMessage(
        'That video is ${formatBytes(bytes)}. The limit is '
        '${formatBytes(kMaxVideoBytes)} — please trim or compress it.',
        isError: true,
      );
      return;
    }

    if (!mounted) return;
    setState(() {
      _videoFile = file;
      _videoBytes = bytes;
    });
  }

  Future<void> _pickThumbnail() async {
    final pickedFile =
        await ImagePicker().pickImage(source: ImageSource.gallery);
    if (pickedFile == null) return;

    final file = File(pickedFile.path);
    final bytes = await file.length();
    if (bytes > kMaxThumbnailBytes) {
      _showMessage(
        'That thumbnail is ${formatBytes(bytes)}. The limit is '
        '${formatBytes(kMaxThumbnailBytes)}.',
        isError: true,
      );
      return;
    }

    if (!mounted) return;
    setState(() {
      _thumbnailFile = file;
      _thumbnailBytes = bytes;
    });
  }

  /// Throttled so a 50 MB upload repaints ~100 times (once per percent) rather
  /// than once per 64 KB chunk.
  void _onUploadProgress(UploadProgress progress) {
    if (!mounted) return;
    final previous = _progress;
    final changed = previous == null ||
        previous.stage != progress.stage ||
        previous.percent != progress.percent;
    if (!changed) return;
    setState(() => _progress = progress);
  }

  Future<void> _uploadCourse() async {
    if (!_formKey.currentState!.validate()) return;

    if (_videoFile == null || _thumbnailFile == null) {
      _showMessage('Please select both a video and a thumbnail');
      return;
    }

    setState(() {
      _isLoading = true;
      _progress = null;
    });

    try {
      final userId = supabase.auth.currentUser?.id;
      if (userId == null) {
        if (!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Your session expired. Please sign in again.'),
            backgroundColor: Colors.red,
          ),
        );
        return;
      }

      // Upload video + thumbnail to Supabase Storage concurrently, with
      // explicit content types and unique per-user object paths.
      final uploadResult = await uploadCourseMedia(
        userId: userId,
        videoFile: _videoFile!,
        thumbnailFile: _thumbnailFile!,
        onProgress: _onUploadProgress,
      );

      if (!uploadResult.success) {
        _showMessage(uploadResult.error ?? 'Media upload failed', isError: true);
        return; // `finally` still clears the loading state.
      }

      // Insert the course row (id + created_at are generated by the database).
      // `video_url` holds the private object key, not a public link — playback
      // URLs are signed per request by the `get-course-video` function.
      await supabase.from('courses').insert({
        'title': _titleController.text.trim(),
        'description': _descriptionController.text.trim(),
        'price': double.tryParse(_priceController.text.trim()) ?? 0,
        'category': _selectedCategory,
        'author': _authorController.text.trim(),
        'video_url': uploadResult.videoPath,
        'thumbnail_url': uploadResult.thumbnailUrl,
        'user_id': userId,
      });

      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Course created successfully!')),
      );

      _formKey.currentState!.reset();
      _videoFile = null;
      _thumbnailFile = null;
      _videoBytes = 0;
      _thumbnailBytes = 0;
      _selectedCategory = null;

      Navigator.pop(context);
    } catch (e) {
      _showMessage('Failed to create course: $e', isError: true);
    } finally {
      // Guarded: every path above can leave this widget unmounted, and an
      // unguarded setState here throws out of `finally`.
      if (mounted) {
        setState(() {
          _isLoading = false;
          _progress = null;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Create Course',
            style: TextStyle(
                color: AppColors.primaryColor,
                fontSize: 18.sp,
                fontWeight: FontWeight.bold)),
        backgroundColor: Colors.white,
        iconTheme: const IconThemeData(color: AppColors.primaryColor),
        elevation: 0,
      ),
      body: Padding(
        padding: EdgeInsets.symmetric(horizontal: 24.0.w, vertical: 16.0.h),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              TextFormField(
                controller: _titleController,
                decoration: InputDecoration(
                  labelText: 'Course Title',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12.0),
                  ),
                ),
                validator: (value) => value == null || value.isEmpty
                    ? 'Please enter a course title'
                    : null,
              ),
              SizedBox(height: 20.h),
              TextFormField(
                controller: _descriptionController,
                decoration: InputDecoration(
                  labelText: 'Course Description',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12.0),
                  ),
                ),
                maxLines: 5,
                validator: (value) => value == null || value.isEmpty
                    ? 'Please enter a course description'
                    : null,
              ),
              SizedBox(height: 20.h),
              DropdownButtonFormField<String>(
                value: _selectedCategory,
                decoration: InputDecoration(
                  labelText: 'Category',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12.0),
                  ),
                ),
                items: _categories.map((String category) {
                  return DropdownMenuItem<String>(
                    value: category,
                    child: Text(category, style: TextStyle(fontSize: 16.sp)),
                  );
                }).toList(),
                onChanged: (value) => setState(() => _selectedCategory = value),
                validator: (value) => value == null || value.isEmpty
                    ? 'Please select a category'
                    : null,
              ),
              SizedBox(height: 20.h),
              TextFormField(
                keyboardType: TextInputType.number,
                controller: _priceController,
                decoration: InputDecoration(
                  labelText: 'Input Price',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12.0),
                  ),
                ),
                validator: (value) => value == null || value.isEmpty
                    ? 'Please enter a course price'
                    : null,
              ),
              SizedBox(height: 20.h),
              TextFormField(
                controller: _authorController,
                decoration: InputDecoration(
                  labelText: 'Author Name',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12.0),
                  ),
                ),
                validator: (value) => value == null || value.isEmpty
                    ? 'Please enter author name'
                    : null,
              ),
              SizedBox(height: 20.h),
              ElevatedButton.icon(
                onPressed: _pickVideo,
                icon: Icon(Icons.video_library, color: AppColors.primaryColor),
                label: Text('Upload Video',
                    style: TextStyle(color: AppColors.primaryColor)),
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColors.lightGrey,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12.r),
                  ),
                ),
              ),
              if (_videoFile != null)
                Padding(
                  padding: EdgeInsets.symmetric(vertical: 10.h),
                  child: Text(
                    'Selected video: ${_videoFile!.path.split('/').last} '
                    '(${formatBytes(_videoBytes)})',
                    style: TextStyle(color: AppColors.primaryColor),
                  ),
                ),
              SizedBox(height: 20.h),
              ElevatedButton.icon(
                onPressed: _pickThumbnail,
                icon: Icon(Icons.image, color: AppColors.primaryColor),
                label: Text('Upload Thumbnail',
                    style: TextStyle(color: AppColors.primaryColor)),
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColors.lightGrey,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12.r),
                  ),
                ),
              ),
              if (_thumbnailFile != null)
                Padding(
                  padding: EdgeInsets.symmetric(vertical: 10.h),
                  child: Text(
                    'Selected thumbnail: ${_thumbnailFile!.path.split('/').last} '
                    '(${formatBytes(_thumbnailBytes)})',
                    style: TextStyle(color: AppColors.primaryColor),
                  ),
                ),
              SizedBox(height: 20.h),
              if (_isLoading)
                UploadProgressCard(progress: _progress)
              else
                PrimaryButton(
                  label: 'Create Course',
                  isLoading: false,
                  onPressed: _uploadCourse,
                ),
            ],
          ),
        ),
      ),
    );
  }

}
